### ISSUE TITLE
ActionController::RoutingError (No route matches [GET] "/assets/hover.css.map"):

### ISSUE THREAD

**Issue by AlirioDS** [Leyka/hover-rails#2]
This problem when update from hover-rails (2.0.2) to 2.3.2
Rails 5.2.1
Ruby 2.5.1p57
Bundler version 1.17.1

**Comment by Leyka** [comment]
Thanks for the report @aliaz0990
I couldn't reproduce the problem on my side, but I added `hover.css.map`
Tell me if this did the trick for you

**Comment by AlirioDS** [comment]
its resolve this... thanks...
